server.port=${SPRING_BOOT_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mnist_database}
spring.datasource.username=${DB_USER:mnist_user}
spring.datasource.password=${DB_PASSWORD:mnist_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jackson.serialization.write-dates-as-timestamps=false

app.ml-service-url=${ML_SERVICE_URL:http://localhost:5000}
